version: "3.9"
services:
  mongodb:
    image: "mongo:4.4.12-focal"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: strengGeheim
    ports:
        - "27017:27017"
    networks:
      nibelheim_ts_dao
  
networks:
  nibelheim_ts_dao
